export const SELECTION_COLUMN_ID = '__SELECTION__';
export const FLEX_COLUMN_ID = '__FLEX__';
export const ACTIONS_COLUMN_ID = '__ACTIONS__';

export const PREDEFINED_COLUMN_IDS = [SELECTION_COLUMN_ID, FLEX_COLUMN_ID, ACTIONS_COLUMN_ID];
